name: Build and Release Package

on:
  push:
    branches: [ main ]
    paths:
      - 'PKGBUILD'
      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: archlinux:base-devel
    
    steps:
      - uses: actions/checkout@v3

      # Install dependencies including zstd
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git zstd

      # Create build user
      - name: Create build user
        run: |
          useradd -m builder
          chown -R builder:builder .

      # Build package
      - name: Build package
        run: |
          su builder -c 'PKGEXT=.pkg.tar.zst makepkg -sf --noconfirm'

      # Test original package compression
      - name: Test package compression
        run: |
          zstd -t *.pkg.tar.zst
          tar --zstd -tvf *.pkg.tar.zst || exit 1

      # Create latest version copy AFTER testing original
      - name: Create latest version copy
        run: |
          cp sd-zfs-hook-*.pkg.tar.zst sd-zfs-hook-latest.pkg.tar.zst
          # Test the copy specifically
          zstd -t sd-zfs-hook-latest.pkg.tar.zst
          tar --zstd -tvf sd-zfs-hook-latest.pkg.tar.zst || exit 1

      # Create GitHub release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          files: |
            sd-zfs-hook-*.pkg.tar.zst
            sd-zfs-hook-latest.pkg.tar.zst
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
